#!/bin/sh

# This script calls utilities.py with the configuration defined here.
# Run ./utilities.py to display explanation of variables

export C5_HOST="127.0.0.1"
export C5_IP="127.0.0.1"
export C5_ROOT="debian"
export C5_LOGIN="exco"
export C5_HTTP="4201"
export C5_SOCK="4202"
export C5_MAIL="thierry.excoffier@univ-lyon1.fr"
export C5_CERT="SS"
export C5_URL="$C5_HOST:4201"
export C5_WEBSOCKET="$C5_HOST:4202"
export C5_REDIRECT=''
export C5_VALIDATE=''
export C5_LOCAL="1"
export C5_LDAP="ldaps://192.168.0.1:636"
export C5_LDAP_LOGIN="admin"
export C5_LDAP_PASSWORD="admin"
export C5_LDAP_BASE="DC=univ-lyon1,DC=fr"

./utilities.py $@

