#!/bin/sh

# Call utilities.py with the configuration defined.

export C5_HOST="134.214.55.164"
export C5_ROOT="debian"
export C5_LOGIN="c5"
export C5_HTTP="4201"
export C5_SOCK="4202"
export C5_MAIL="thierry.excoffier@univ-lyon1.fr"
export C5_CERT="NGINX"
export C5_URL="c5.univ-lyon1.fr"
export C5_WEBSOCKET="c5.univ-lyon1.fr/WebSocket"
export C5_REDIRECT='https://cas.univ-lyon1.fr/login?service='
export C5_VALIDATE='https://cas.univ-lyon1.fr/cas/validate?service=%s&ticket=%s'

./utilities.py $@

