#!/bin/sh
# Argument 1 : the python file to compile WITHOUT .py EXTENSION

PY=$1.py
JS=$1.js
JSON=$1.json

if [ -e $JS ]
then
    mv $JS $JS~
fi
if [ -e $JSON ]
then
    mv $JSON $JSON~
fi

restore() {
    if [ -e $JS~ ]
    then
        mv $JS~ $JS
    fi
    if [ -e $JSON~ ]
    then
        mv $JSON~ $JSON
    fi
    # rm $PY.xxx
}

BEFORE=''
case $1 in
	COMPILE*)
		COMPILER=$(echo $1 | sed -e 's,/.*,,' | tr '[A-Z]' '[a-z]')
		FILES="$PY"
		SESSION=$(
			echo
			echo 'if not Compile.worker: eval("new Session([' \
                $(grep '^class.*(Question)' $PY |
                  tr '\n' '%' |
                  sed -r -e 's/%*class *([^%]*)\(Question\)[^%]*/new \1(),/g' -e 's/,%$//'
                 ) '])")'
			)
		[ -d $1 ] && chmod 700 $1
        BEFORE="importScripts('JS/$COMPILER.js' + location.search)"
		;;
    compile_*)
		COMPILER=
		FILES="compatibility.py xxx_local.py options.py compile.py question.py $PY"
		JS=JS/$JS
		;;
	*)
		COMPILER=
		FILES="compatibility.py xxx_local.py options.py $PY"
		JS=JS/$JS
		;;
esac

echo "$BEFORE" >$PY.xxx
if cat $FILES >>$PY.xxx
then
    :
else
    restore
    exit 1
fi

echo "$SESSION" >> $PY.xxx

if nodejs RapydScript/bin/rapydscript --prettify --bare $PY.xxx >$JS
then
    echo "$PY → $JS OK"
else
    echo "$PY → $JS FAIL"
    restore
    exit 1
fi

if [ "$COMPILER" != "" ]
then
	if cat options.py compile.py $COMPILER.py question_before.py $PY question_after.py |
		tee xxx.py |
		python3 >$JSON
    then
        echo "$PY → $JSON OK"
    else
        echo "$PY → $JSON FAIL"
        restore
        exit 1
    fi
fi

rm $PY.xxx
